version: "3.7"

volumes:
  pg_data:

networks:
  backend_network:

services:
  api:
    image: localhost:5000/fibness/api-stage:latest
    depends_on:
      - pg
    environment:
      NODE_ENV: stage
    networks:
      - backend_network
    ports:
      - "3001:3000"
  
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_STAGE_USR}
      POSTGRES_PASSWORD: ${DB_STAGE_PSW}
      POSTGRES_DB: fibness
    networks:
      - backend_network
    ports:
      - "54321:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
