version: "3.7"

services:
  api:
    depends_on:
      - pg-test
    environment:
      NODE_ENV: test
    #network_mode: host
    ports:
      - "3002:3000"
  
  pg-test:
    image: postgres:12
    #env_file:
    #  - .envs/.pg.env
    environment:
      POSTGRES_USER: fibness
      POSTGRES_PASSWORD: fibness
      POSTGRES_DB: fibness
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d/