version: "3.7"

volumes:
  pg-db-stage:

services:
  api:
    depends_on:
      - pg-stage
    environment:
      NODE_ENV: stage
    ports:
      - "3001:3000"
  
  pg-stage:
    image: postgres:12
    #env_file:
    #  - .envs/.pg.env
    volumes:
      - pg-db-stage:/var/lib/postgresql/data
    ports:
      - "54321:5432"