version: "3.7"

networks:
  backend_network:

services:
  api:
    build: .
    depends_on:
      - pg
    environment:
      NODE_ENV: test
      NODE_CONFIG_ENV: jenkins
    networks:
      - backend_network
    volumes:
      - ./reports:/home/api/reports
  
  pg:
    image: postgres:12
    environment:
      POSTGRES_USER: fibness
      POSTGRES_PASSWORD: fibness
      POSTGRES_DB: test
    networks:
      - backend_network
