version: "3.7"

volumes:
  pg_data:

services:
  api:
    build: .
    depends_on:
      - pg
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://fibness:fibness@pg:5432/fibness
    ports:
      - "3000:3000"
    volumes:
      - .:/home/api
      - /home/app/node_modules
  
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: fibness
      POSTGRES_PASSWORD: fibness
      POSTGRES_DB: fibness
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d/
      
