version: "3.7"

volumes:
  pg-db:

services:
  api:
    depends_on:
      - pg
    network_mode: host
    volumes:
      - .:/home/api
      - /home/app/node_modules
    environment:
      NODE_ENV: development
  
  pg:
    image: postgres:12
    env_file:
      - .envs/.pg.env
    ports:
      - "5432:5432"
    volumes:
      - pg-db:/var/lib/postgresql/data
  
  pg-test:
    image: postgres:12
    ports:
      - "54322:5432"
    env_file:
      - .envs/.pg.env