version: "3.7"

volumes:
  pg-db-stage:

networks:
  fibness-backend_stage:

services:
  api-stage:
    image: fibness/api-stage:latest
    depends_on:
      - pg-stage
    environment:
      NODE_ENV: stage
    networks:
      - fibness-backend_stage
    ports:
      - "3001:3000"
  
  pg-stage:
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_STAGE_USR}
      POSTGRES_PASSWORD: ${DB_STAGE_PSW}
      POSTGRES_DB: fibness
    networks:
      - fibness-backend_stage
    ports:
      - "54321:5432"
    volumes:
      - pg-db-stage:/var/lib/postgresql/data